---
title: "QAA"
author: "Zach Girard"
date: "2024-09-06"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r,}
Trimmed_3_2B_R1 = read_table("Trimmed_3_2B_control_S3_L008_R1_001_Length_distribution.txt")
colnames(Trimmed_3_2B_R1) = "Lengths"



Trimmed_3_2B_R2 = read_table("Trimmed_3_2B_control_S3_L008_R2_001_Length_distribution.txt", col_names = "Lengths")
colnames(Trimmed_3_2B_R2) = "Lengths"


Trimmed_28_4D_R1 = read_table("Trimmed_28_4D_mbnl_S20_L008_R1_001_Length_distribution.txt", col_names = "Lengths")
colnames(Trimmed_28_4D_R1) = "Lengths"

Trimmed_28_4D_R2 = read_table("Trimmed_28_4D_mbnl_S20_L008_R2_001_Length_distribution.txt")
colnames(Trimmed_28_4D_R2) = "Lengths"

```

```{r}
#First make a new column in each that will be 
# a variable to identify where they came from later.
Trimmed_28_4D_R1$Read <- 'R1'
Trimmed_28_4D_R2$Read <- 'R2'

# and combine int new data frame
Trimmed_28_Lengths <- rbind(Trimmed_28_4D_R1, Trimmed_28_4D_R2)


ggplot(Trimmed_28_Lengths, aes(Lengths, fill = Read)) +
   geom_histogram(alpha = 0.5, aes(), position = 'identity', binwidth = 1) +
  theme_bw()+
  scale_x_continuous(breaks = seq(0,101, 10)) +
  labs(title="Length distribution of Trimmed 28_4D_mbnl_S20_L008 \n Read 1 and Read 2 sequence reads", y = "Count" )


```
```{r}
Trimmed_3_2B_R1$Read <- 'R1'
Trimmed_3_2B_R2$Read <- 'R2'

# and combine int new data frame
Trimmed_3_2B_Lengths <- rbind(Trimmed_3_2B_R1, Trimmed_3_2B_R2)


ggplot(Trimmed_3_2B_Lengths, aes(Lengths, fill = Read)) +
   geom_histogram(alpha = 0.5, aes(), position = 'identity', binwidth = 1) +
  theme_bw()+
  scale_x_continuous(breaks = seq(0,101, 10)) +
  labs(title="Length distribution of Trimmed 3_2B_control_S3_L008 \n Read 1 and Read 2 sequence reads", y = "Count" )
```

